default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight using repo exportOptions plist"
  lane :ci_beta do
    UI.message("ci_beta lane has been disabled in this repository to prevent automated uploads to App Store / TestFlight.")
  end
end
